# Generated by Django 3.2.9 on 2021-12-30 09:59

import datetime

import scouts_auth.inuits.models.fields.timezone_aware_date_time_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutsuser',
            name='last_authenticated',
            field=scouts_auth.inuits.models.fields.timezone_aware_date_time_field.TimezoneAwareDateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='scoutsuser',
            name='last_refreshed',
            field=scouts_auth.inuits.models.fields.timezone_aware_date_time_field.TimezoneAwareDateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
