# Generated by Django 3.2.9 on 2021-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutsuser',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('I', 'Mixed'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=16),
        ),
    ]
