# Generated by Django 4.2.12 on 2024-05-06 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scouts_auth", "0003_auto_20220105_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persistedfile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instance created by",
            ),
        ),
        migrations.AlterField(
            model_name="persistedfile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instance last update by",
            ),
        ),
    ]
