# Generated by Django 3.2.9 on 2022-05-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelassistanceinsurance',
            options={'managed': True},
        ),
    ]
