# Generated by Django 3.2.9 on 2022-05-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0004_alter_travelassistanceinsurance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelassistanceinsurance',
            options={'managed': True},
        ),
    ]
