# Generated by Django 3.2.9 on 2022-05-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0009_auto_20220525_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonmember',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='travelassistanceinsurance',
            options={'managed': False},
        ),
    ]
