# Generated by Django 3.2.9 on 2022-06-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0010_auto_20220525_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'managed': True},
        ),
    ]
