# Generated by Django 3.2.9 on 2022-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0014_alter_temporaryvehicleinsurance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryvehicleinsurance',
            name='_vehicle_id',
            field=models.UUIDField(blank=True, db_column='inuits_vehicle_id', default=None, null=True),
        ),
    ]
