# Generated by Django 3.2.9 on 2022-06-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0016_alter_temporaryvehicleinsurance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelassistanceinsurance',
            options={'managed': True},
        ),
    ]
