# Generated by Django 3.2.9 on 2022-06-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0018_auto_20220607_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelassistanceinsurance',
            options={'managed': False},
        ),
    ]
