# Generated by Django 3.2.2 on 2021-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(db_column='adres_id', primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='straat', max_length=100)),
                ('number', models.CharField(db_column='nummer', max_length=5)),
                ('letter_box', models.CharField(blank=True, db_column='bus', max_length=5, null=True)),
                ('postcode', models.CharField(db_column='postcode', max_length=4)),
                ('city', models.CharField(db_column='gemeente', max_length=40)),
            ],
            options={
                'db_table': 'vrzk_adres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(db_column='lidid', primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='naam', max_length=25)),
                ('first_name', models.CharField(db_column='voornaam', max_length=15)),
                ('phone_number', models.CharField(blank=True, db_column='telefoon', max_length=15)),
                ('_birth_date', models.DateField(blank=True, db_column='geboortedatum', null=True)),
                ('membership_number', models.BigIntegerField(db_column='lidnr', null=True)),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('group_admin_id', models.CharField(blank=True, db_column='ga_id', max_length=255)),
            ],
            options={
                'db_table': 'vrzkleden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonMember',
            fields=[
                ('id', models.AutoField(db_column='nietlidid', primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='naam', max_length=25)),
                ('first_name', models.CharField(db_column='voornaam', max_length=15)),
                ('phone_number', models.CharField(blank=True, db_column='telefoon', max_length=15)),
                ('_birth_date', models.DateField(blank=True, db_column='geboortedatum', null=True)),
                ('street', models.CharField(blank=True, db_column='straat', max_length=100)),
                ('number', models.CharField(blank=True, db_column='nr', max_length=5)),
                ('letter_box', models.CharField(blank=True, db_column='bus', max_length=5)),
                ('postcode', models.IntegerField(blank=True, db_column='postcode', null=True)),
                ('city', models.CharField(blank=True, db_column='gemeente', max_length=40)),
                ('comment', models.CharField(blank=True, db_column='commentaar', max_length=500)),
            ],
            options={
                'db_table': 'vrzknietleden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InuitsNonMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=5)),
                ('letter_box', models.CharField(blank=True, max_length=5)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('comment', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
