# Generated by Django 3.2.8 on 2021-11-17 08:59

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='adres_id', primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='straat', max_length=100)),
                ('number', models.CharField(db_column='nummer', max_length=5)),
                ('letter_box', models.CharField(blank=True, db_column='bus', max_length=5, null=True)),
                ('postcode', models.CharField(db_column='postcode', max_length=4)),
                ('city', models.CharField(db_column='gemeente', max_length=40)),
            ],
            options={
                'db_table': 'vrzk_adres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('last_name', models.CharField(db_column='naam', max_length=25)),
                ('first_name', models.CharField(db_column='voornaam', max_length=15)),
                ('phone_number', models.CharField(blank=True, db_column='telefoon', max_length=15)),
                ('_birth_date', models.DateField(blank=True, db_column='geboortedatum', null=True)),
                ('id', models.AutoField(db_column='lidid', primary_key=True, serialize=False)),
                ('membership_number', models.BigIntegerField(db_column='lidnr')),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('group_admin_id', models.CharField(blank=True, db_column='ga_id', max_length=255)),
            ],
            options={
                'db_table': 'vrzkleden',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonMember',
            fields=[
                ('last_name', models.CharField(db_column='naam', max_length=25)),
                ('first_name', models.CharField(db_column='voornaam', max_length=15)),
                ('phone_number', models.CharField(blank=True, db_column='telefoon', max_length=15)),
                ('_birth_date', models.DateField(blank=True, db_column='geboortedatum', null=True)),
                ('id', models.AutoField(db_column='nietlidid', primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, db_column='straat', max_length=100)),
                ('number', models.CharField(blank=True, db_column='nr', max_length=5)),
                ('letter_box', models.CharField(blank=True, db_column='bus', max_length=5)),
                ('postcode', models.IntegerField(blank=True, db_column='postcode', null=True)),
                ('city', models.CharField(blank=True, db_column='gemeente', max_length=40)),
                ('comment', models.CharField(blank=True, db_column='commentaar', max_length=500)),
            ],
            options={
                'db_table': 'vrzknietleden',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InuitsNonMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=5)),
                ('letter_box', models.CharField(blank=True, max_length=5)),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('group_number', models.CharField(max_length=6)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonMemberInuitsTemplate',
            fields=[
                ('non_member', models.OneToOneField(db_constraint=django.db.models.constraints.UniqueConstraint, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.nonmember')),
                ('inuits_non_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.inuitsnonmember')),
            ],
        ),
    ]
