# Generated by Django 3.2.8 on 2021-11-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonmemberinuitstemplate',
            name='inuits_non_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='members.inuitsnonmember'),
        ),
    ]
