# Generated by Django 3.2.2 on 2021-06-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inuitsnonmember',
            name='group_number',
            field=models.CharField(default='test', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='postcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
