# Generated by Django 3.2.2 on 2021-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210601_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
