# Generated by Django 3.2.2 on 2021-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_inuitsnonmember_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='adres_id', primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='straat', max_length=100)),
                ('number', models.CharField(db_column='nummer', max_length=5)),
                ('letter_box', models.CharField(blank=True, db_column='bus', max_length=5, null=True)),
                ('postcode', models.CharField(db_column='postcode', max_length=4)),
                ('city', models.CharField(db_column='gemeente', max_length=40)),
            ],
            options={
                'db_table': 'vrzk_adres',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nonmember',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
