# Generated by Django 3.2.4 on 2021-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210610_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
