# Generated by Django 3.2.4 on 2021-07-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210709_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='inuitsnonmember',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
