# Generated by Django 3.2.5 on 2021-09-27 10:29

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_inuitsnonmember_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='NonMemberInuitsTemplate',
            fields=[
                ('non_member', models.OneToOneField(db_constraint=django.db.models.constraints.UniqueConstraint, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.nonmember')),
                ('inuits_non_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.inuitsnonmember')),
            ],
        ),
    ]
