# Generated by Django 3.2.8 on 2021-10-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20210927_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inuitsnonmember',
            old_name='sex',
            new_name='gender',
        ),
    ]
