# Generated by Django 3.2.9 on 2022-05-17 11:04

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsclaimvictim',
            name='letter_box',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inuitsnonmember',
            name='letter_box',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=5, null=True),
        ),
    ]
