# Generated by Django 3.2.9 on 2021-12-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inuitsnonmember',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='inuitsnonmember',
            name='searchable',
        ),
        migrations.AddField(
            model_name='inuitsnonmembertemplate',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
