# Generated by Django 3.2.9 on 2021-12-22 16:11

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0001_initial'),
        ('people', '0002_auto_20211222_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsnonmembertemplate',
            name='non_member',
            field=models.OneToOneField(db_constraint=django.db.models.constraints.UniqueConstraint, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='template', serialize=False, to='scouts_insurances.nonmember'),
        ),
    ]
