# Generated by Django 4.2.11 on 2024-06-21 13:44

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_alter_inuitsclaimvictim_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inuitsclaimvictim",
            name="first_name",
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inuitsclaimvictim",
            name="last_name",
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inuitsnonmember",
            name="first_name",
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inuitsnonmember",
            name="last_name",
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=255),
        ),
    ]
