# Generated by Django 3.2.9 on 2021-12-22 17:42

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_inuitsnonmembertemplate_non_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inuitsnonmembertemporaryinsurancetemplate',
            name='non_member',
        ),
        migrations.RemoveField(
            model_name='inuitsnonmembertemporaryinsurancetemplate',
            name='temporary_insurance',
        ),
        migrations.RemoveField(
            model_name='inuitsnonmembertemporaryvehicleinsurancetemplate',
            name='non_member',
        ),
        migrations.RemoveField(
            model_name='inuitsnonmembertemporaryvehicleinsurancetemplate',
            name='temporary_vehicle_insurance',
        ),
        migrations.RemoveField(
            model_name='inuitsnonmembertravelinsurancetemplate',
            name='non_member',
        ),
        migrations.RemoveField(
            model_name='inuitsnonmembertravelinsurancetemplate',
            name='travel_assistance',
        ),
        migrations.AddField(
            model_name='inuitsnonmember',
            name='company_name',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='InuitsNonMemberEquipmentTemplate',
        ),
        migrations.DeleteModel(
            name='InuitsNonMemberTemporaryInsuranceTemplate',
        ),
        migrations.DeleteModel(
            name='InuitsNonMemberTemporaryVehicleInsuranceTemplate',
        ),
        migrations.DeleteModel(
            name='InuitsNonMemberTravelInsuranceTemplate',
        ),
    ]
