# Generated by Django 3.2.9 on 2021-12-13 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import scouts_auth.inuits.models.fields.django_shorthand_model_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scouts_insurances', '0001_initial'),
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInsuranceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventInsuranceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('group_group_admin_id', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=6)),
                ('date_of_accident', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalDateTimeField(blank=True, null=True)),
                ('declarant_city', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=40)),
                ('bank_account', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=30)),
                ('location', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=128)),
                ('activity', models.CharField(max_length=1024)),
                ('activity_type', jsonfield.fields.JSONField(max_length=128)),
                ('used_transport', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=30)),
                ('description', scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=1024)),
                ('damage_type', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=128)),
                ('involved_party_name', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=1024)),
                ('involved_party_description', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=1024)),
                ('involved_party_birthdate', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalDateField(blank=True, null=True)),
                ('official_report_description', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=1024)),
                ('pv_number', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=30)),
                ('witness_name', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=128)),
                ('witness_description', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=1024)),
                ('leadership_description', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=1024)),
                ('note', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=1024)),
                ('case_number', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances_insuranceclaim_created', to=settings.AUTH_USER_MODEL, verbose_name='Instance created by')),
                ('declarant', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarant', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances_insuranceclaim_updated', to=settings.AUTH_USER_MODEL, verbose_name='Instance last update by')),
            ],
            options={
                'permissions': [('add_insuranceclaim_note', 'User can add a note to a claim'), ('view_insuranceclaim_note', 'Administrative users can view a claim note'), ('add_insuranceclaim_case_number', 'Users can add a claim case number'), ('view_insuranceclaim_case_number', 'Administrative users can view a claim case number'), ('list_insuranceclaims', 'User can view a list of claims'), ('view_insuranceclaimattachment_filename', 'User can view the filename of a claim attachment')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances_insurancedraft_created', to=settings.AUTH_USER_MODEL, verbose_name='Instance created by')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='insurance_drafts', to='scouts_insurances.insurancetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances_insurancedraft_updated', to=settings.AUTH_USER_MODEL, verbose_name='Instance last update by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claim', to='scouts_auth.persistedfile')),
                ('insurance_claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='insurances.insuranceclaim')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
