# Generated by Django 3.2.2 on 2021-06-10 13:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_auto_20210610_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInsurance',
            fields=[
                ('id', models.AutoField(db_column='verzekeringsid', primary_key=True, serialize=False)),
                ('_status', models.IntegerField(blank=True, db_column='status', null=True)),
                ('invoice_number', models.IntegerField(blank=True, db_column='factuurnr', null=True)),
                ('invoice_date', models.DateTimeField(blank=True, db_column='facturatiedatum', null=True)),
                ('_group_number', models.CharField(db_column='groepsnr', max_length=6)),
                ('_group_name', models.CharField(db_column='groepsnaam', max_length=50)),
                ('_group_location', models.CharField(db_column='groepsplaats', max_length=50)),
                ('total_cost', models.DecimalField(db_column='totkostprijs', decimal_places=2, max_digits=7, null=True)),
                ('comment', models.CharField(blank=True, db_column='opmerking', max_length=500)),
                ('vvks_comment', models.CharField(blank=True, db_column='vvksmopmerking', max_length=500)),
                ('_printed', models.CharField(db_column='afgedrukt', default='N', max_length=1)),
                ('_finished', models.CharField(db_column='afgewerkt', default='N', max_length=1)),
                ('_listed', models.CharField(db_column='lijstok', default='N', max_length=1)),
                ('created_on', models.DateTimeField(db_column='datumvaninvulling', null=True)),
                ('_start_date', models.DateField(db_column='begindatum', null=True)),
                ('_end_date', models.DateField(db_column='einddatum', null=True)),
                ('payment_date', models.DateTimeField(blank=True, db_column='betalingsdatum', null=True)),
            ],
            options={
                'db_table': 'vrzkverzekeringen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.IntegerField(db_column='verzekeringstypeid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='verzekeringstype', max_length=30)),
                ('description', models.CharField(db_column='verzekeringstypeomschr', max_length=50)),
                ('max_term', models.CharField(db_column='maxtermijn', max_length=10)),
            ],
            options={
                'db_table': 'vrzkverzekeringstypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonMemberTemporaryInsurance',
            fields=[
                ('non_member_id', models.ForeignKey(db_column='nietledenid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.nonmember')),
            ],
            options={
                'db_table': 'vrzknietledentijd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantTemporaryVehicleInsurance',
            fields=[
                ('participant', models.ForeignKey(db_column='bestuurderid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.nonmember')),
                ('type', models.CharField(choices=[('Bestuurder', 'Bestuurder'), ('Eigenaar', 'Eigenaar')], db_column='soort', max_length=10)),
            ],
            options={
                'db_table': 'vrzktijdautonietleden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantTravelAssistanceInsurance',
            fields=[
                ('participant', models.ForeignKey(db_column='passagierid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.nonmember')),
            ],
            options={
                'db_table': 'vrzkassistpassagier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityInsurance',
            fields=[
                ('insurance_parent', models.OneToOneField(db_column='verzekeringsid', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='activity_child', serialize=False, to='insurances.baseinsurance')),
                ('nature', models.CharField(db_column='aardactiviteit', max_length=500)),
                ('_group_size', models.IntegerField(db_column='aantgroep', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('postcode', models.IntegerField(db_column='postcode', null=True)),
                ('city', models.CharField(db_column='gemeente', max_length=40)),
            ],
            options={
                'db_table': 'vrzktypeeenact',
                'managed': False,
            },
            bases=('insurances.baseinsurance',),
        ),
        migrations.CreateModel(
            name='EquipmentInsurance',
            fields=[
                ('insurance_parent', models.OneToOneField(db_column='verzekeringsid', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='equipment_child', serialize=False, to='insurances.baseinsurance')),
                ('nature', models.CharField(db_column='aardactiviteit', max_length=500)),
                ('postcode', models.IntegerField(blank=True, db_column='postcode', null=True)),
                ('city', models.CharField(blank=True, db_column='gemeente', max_length=40)),
                ('_country', models.CharField(blank=True, db_column='land', max_length=45)),
            ],
            options={
                'db_table': 'vrzktypemateriaal',
                'managed': False,
            },
            bases=('insurances.baseinsurance',),
        ),
        migrations.CreateModel(
            name='EventInsurance',
            fields=[
                ('insurance_parent', models.OneToOneField(db_column='verzekeringsid', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='event_child', serialize=False, to='insurances.baseinsurance')),
                ('nature', models.CharField(db_column='aardactiviteit', max_length=500)),
                ('event_size', models.IntegerField(choices=[(1, '1-500 (65,55 eur/dag)'), (2, '500-1000 (131,10 eur/dag)'), (3, '1000-1500 (163,88 eur/dag'), (4, '1500-2500 (229,43 eur/dag)'), (5, 'meer dan 2500 (in overleg met Ethias)')], db_column='aantbezoekers', null=True)),
                ('postcode', models.IntegerField(db_column='postcode', null=True)),
                ('city', models.CharField(db_column='gemeente', max_length=40)),
            ],
            options={
                'db_table': 'vrzktypeevenement',
                'managed': False,
            },
            bases=('insurances.baseinsurance',),
        ),
        migrations.CreateModel(
            name='TemporaryInsurance',
            fields=[
                ('insurance_parent', models.OneToOneField(db_column='verzekeringsid', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='temporary_child', serialize=False, to='insurances.baseinsurance')),
                ('nature', models.CharField(db_column='aardactiviteit', max_length=500)),
                ('postcode', models.IntegerField(blank=True, db_column='postcode', null=True)),
                ('city', models.CharField(blank=True, db_column='gemeente', max_length=40)),
                ('_country', models.CharField(blank=True, db_column='land', max_length=45)),
            ],
            options={
                'db_table': 'vrzktypetijdact',
                'managed': False,
            },
            bases=('insurances.baseinsurance',),
        ),
        migrations.CreateModel(
            name='TemporaryVehicleInsurance',
            fields=[
                ('insurance_parent', models.OneToOneField(db_column='verzekeringsid', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='temporary_vehicle_child', serialize=False, to='insurances.baseinsurance')),
                ('_insurance_option', models.IntegerField(choices=[(1, 'omnium'), (2, 'reeds afgesloten omnium afdekken'), (3, 'huurvoertuigen'), (13, 'omnium + huurvoertuigen'), (23, 'reeds afgesloten omnium afdekken + huurvoertuigen')], db_column='keuze')),
                ('max_coverage', models.CharField(blank=True, choices=[('A', '247,89 EUR'), ('B', '495,79 EUR'), ('C', '743,68 EUR')], db_column='maxdekking', max_length=1, null=True)),
                ('_vehicle_type', models.CharField(blank=True, choices=[('PERSONENWAGEN', 'Personenwagen (maximum 5 passagiers)'), ('MINIBUS', 'Minibus (maximum 8 passagiers)'), ('VRACHTWAGEN', 'Vrachtwagen tot 3.5 ton (maximum 8 passagiers)')], db_column='autotype', max_length=30, null=True)),
                ('_vehicle_brand', models.CharField(blank=True, db_column='automerk', max_length=15, null=True)),
                ('_vehicle_license_plate', models.CharField(blank=True, db_column='autokenteken', max_length=10, null=True)),
                ('_vehicle_construction_year', models.IntegerField(blank=True, db_column='autobouwjaar', null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('_vehicle_chassis_number', models.CharField(db_column='autochassis', max_length=20)),
                ('_vehicle_trailer', models.CharField(choices=[('0', 'Geen'), ('2', '<750kg'), ('3', '>750kg')], db_column='aanhangwagen', default='0', max_length=1)),
            ],
            options={
                'db_table': 'vrzktypetijdauto',
                'managed': False,
            },
            bases=('insurances.baseinsurance',),
        ),
        migrations.CreateModel(
            name='TravelAssistanceInsurance',
            fields=[
                ('insurance_parent', models.OneToOneField(db_column='verzekeringsid', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='travel_assistance_child', serialize=False, to='insurances.baseinsurance')),
                ('_country', models.CharField(db_column='bestemmingsland', max_length=40)),
                ('_vehicle_type', models.CharField(blank=True, db_column='autotype', max_length=30, null=True)),
                ('_vehicle_brand', models.CharField(blank=True, db_column='automerk', max_length=15, null=True)),
                ('_vehicle_license_plate', models.CharField(blank=True, db_column='autokenteken', max_length=10, null=True)),
                ('_vehicle_construction_year', models.IntegerField(blank=True, db_column='autobouwjaar', null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('_vehicle_trailer', models.IntegerField(blank=True, db_column='aanhangwagen', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'db_table': 'vrzktypeethiasassistance',
                'managed': False,
            },
            bases=('insurances.baseinsurance',),
        ),
        migrations.CreateModel(
            name='CostVariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=5, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cost_variables', to='insurances.insurancetype')),
            ],
            options={
                'unique_together': {('key', 'insurance_type')},
            },
        ),
    ]
