# Generated by Django 3.2.8 on 2021-11-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceclaim',
            options={'permissions': [('add_insuranceclaim_note', 'User can add a note to a claim'), ('view_insuranceclaim_note', 'Administrative users can view a claim note'), ('add_insuranceclaim_case_number', 'Users can add a claim case number'), ('view_insuranceclaim_case_number', 'Administrative users can view a claim case number'), ('list_insuranceclaims', 'User can view a list of claims'), ('view_insuranceclaimattachment_filename', 'User can view the filename of a claim attachment')]},
        ),
    ]
