# Generated by Django 3.2.2 on 2021-06-10 13:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costvariable',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
