# Generated by Django 3.2.4 on 2021-06-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_alter_costvariable_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
