# Generated by Django 3.2.4 on 2021-06-14 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_insurancedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
