# Generated by Django 3.2.9 on 2022-06-07 13:03

from django.db import migrations

import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_auto_20220607_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='attachment_name',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=1024, null=True),
        ),
    ]
