# Generated by Django 4.2.12 on 2024-05-06 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insurances", "0005_auto_20220608_1614"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceclaim",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instance created by",
            ),
        ),
        migrations.AlterField(
            model_name="insuranceclaim",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instance last update by",
            ),
        ),
        migrations.AlterField(
            model_name="insurancedraft",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instance created by",
            ),
        ),
        migrations.AlterField(
            model_name="insurancedraft",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instance last update by",
            ),
        ),
    ]
