# Generated by Django 3.2.4 on 2021-07-01 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_auto_20210610_1500'),
        ('insurances', '0006_insurancedraft_insurance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('victim_member_group_admin_id', models.CharField(blank=True, db_column='ga_id', max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_accident', models.DateField()),
                ('activity', models.CharField(max_length=30)),
                ('activity_type', models.CharField(choices=[('REGULAR', 'regular activity'), ('IRREGULAR_LOCATION', 'activity on another location'), ('TRANSPORT', 'transport')], max_length=30)),
                ('used_transport', models.CharField(blank=True, max_length=30, null=True)),
                ('damage_type', models.CharField(choices=[('GLASSES', 'glasses'), ('MATERIAL', 'material')], max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('involved_party_description', models.CharField(blank=True, max_length=30, null=True)),
                ('involved_party_birthdate', models.DateField(blank=True, null=True)),
                ('official_report_description', models.CharField(blank=True, max_length=256, null=True)),
                ('pv_number', models.CharField(blank=True, max_length=30, null=True)),
                ('witness_description', models.CharField(blank=True, max_length=30, null=True)),
                ('leadership_description', models.CharField(blank=True, max_length=30, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('victim_non_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_victim', to='members.inuitsnonmember')),
            ],
        ),
    ]
