# Generated by Django 3.2.4 on 2021-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0007_insuranceclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('GLASSES', 'glasses'), ('MATERIAL', 'material')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='date_of_accident',
            field=models.DateTimeField(),
        ),
    ]
