# Generated by Django 3.2.4 on 2021-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0008_auto_20210701_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='group_number',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
