# Generated by Django 3.2.4 on 2021-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0009_insuranceclaim_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='activity',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='involved_party_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='leadership_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='official_report_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='witness_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
