# Generated by Django 3.2.4 on 2021-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0012_alter_insuranceclaim_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='witness_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
