# Generated by Django 3.2.4 on 2021-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0014_auto_20210728_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
