# Generated by Django 3.2.5 on 2021-08-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0015_insuranceclaim_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='case_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
