# Generated by Django 3.2.5 on 2021-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0016_auto_20210806_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='victim_birth_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
