# Generated by Django 3.2.5 on 2021-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0017_insuranceclaim_victim_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='involved_party_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
