# Generated by Django 3.2.5 on 2021-08-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0018_insuranceclaim_involved_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='victim_email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
