# Generated by Django 3.2.5 on 2021-08-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0019_insuranceclaim_victim_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaimVictim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=5)),
                ('letter_box', models.CharField(blank=True, max_length=5)),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='victim_birth_date',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='victim_email',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='victim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurances.insuranceclaimvictim'),
        ),
    ]
