# Generated by Django 3.2.5 on 2021-08-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_inuitsnonmember_sex'),
        ('insurances', '0021_insuranceclaimvictim_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='victim_member_group_admin_id',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='victim_non_member',
        ),
        migrations.AddField(
            model_name='insuranceclaimvictim',
            name='group_admin_id',
            field=models.CharField(blank=True, db_column='ga_id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaimvictim',
            name='non_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_victim', to='members.inuitsnonmember'),
        ),
    ]
