# Generated by Django 3.2.5 on 2021-08-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0022_auto_20210809_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='legal_representative',
        ),
        migrations.AddField(
            model_name='insuranceclaimvictim',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
