# Generated by Django 3.2.5 on 2021-08-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0023_auto_20210811_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='damage_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
