# Generated by Django 3.2.5 on 2021-09-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0024_alter_insuranceclaim_damage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaimvictim',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown')], max_length=1, null=True),
        ),
    ]
