# Generated by Django 3.2.5 on 2021-10-07 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0025_alter_insuranceclaimvictim_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceclaim',
            options={'permissions': (('can_view_note_and_case_number', 'Administratieve gebruikers kunnen dossiernummer en opmerkingen bekijken'),)},
        ),
        migrations.AlterField(
            model_name='insuranceclaimvictim',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='InsuranceClaimAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'tiff', 'odt', 'pptx', 'docx', 'pdf', 'doc', 'xls'])])),
                ('content_type', models.CharField(max_length=100)),
                ('insurance_claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='insurances.insuranceclaim')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
