# Generated by Django 3.2.5 on 2021-10-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0026_auto_20211007_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceclaimattachment',
            name='insurance_claim',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='attachment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurances.insuranceclaimattachment'),
        ),
    ]
