# Generated by Django 3.2.5 on 2021-10-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0027_auto_20211007_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceclaim',
            old_name='attachment',
            new_name='file',
        ),
    ]
