# Generated by Django 3.2.5 on 2021-10-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0028_rename_attachment_insuranceclaim_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurances.insuranceclaimattachment'),
        ),
    ]
