# Generated by Django 3.2.5 on 2021-10-10 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0029_alter_insuranceclaim_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='file',
        ),
        migrations.AddField(
            model_name='insuranceclaimattachment',
            name='insurance_claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurances.insuranceclaim'),
        ),
        migrations.AlterField(
            model_name='insuranceclaimattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'tiff', 'odt', 'pptx', 'docx', 'pdf', 'doc', 'xls'])]),
        ),
    ]
