# Generated by Django 3.2.8 on 2021-10-18 14:56

from django.db import migrations, models
import inuits.files.validators


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0031_alter_insuranceclaimattachment_insurance_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceclaimvictim',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='insuranceclaimattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[inuits.files.validators.validate_file_extension]),
        ),
    ]
