# Generated by Django 3.2.8 on 2021-11-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0032_auto_20211018_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceclaim',
            options={'permissions': [('can_view_note_and_case_number', 'Administratieve gebruikers kunnen dossiernummer en opmerkingen bekijken'), ('claims.can_add_claim', ''), ('claims.can_view_claim', ''), ('claims.can_list_claims', ''), ('claims.can_add_comment', 'https://redmine.inuits.eu/issues/78579'), ('claims.can_view_comment', 'https://redmine.inuits.eu/issues/78579'), ('claims.can_add_case_number', 'https://redmine.inuits.eu/issues/78579'), ('claims.can_view_case_number', 'https://redmine.inuits.eu/issues/78579'), ('claims.can_view_attachment_filename', '')]},
        ),
    ]
