# Generated by Django 3.2.8 on 2021-11-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0033_alter_insuranceclaim_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceclaim',
            options={'permissions': [('can_view_note_and_case_number', 'Administratieve gebruikers kunnen dossiernummer en opmerkingen bekijken'), ('can_add_claim', ''), ('can_view_claim', ''), ('can_list_claims', ''), ('can_add_comment', 'https://redmine.inuits.eu/issues/78579'), ('can_view_comment', 'https://redmine.inuits.eu/issues/78579'), ('can_add_case_number', 'https://redmine.inuits.eu/issues/78579'), ('can_view_case_number', 'https://redmine.inuits.eu/issues/78579'), ('can_view_attachment_filename', '')]},
        ),
    ]
