# Generated by Django 3.2.2 on 2021-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("insurances", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                (
                    "insurance_types",
                    models.ManyToManyField(related_name="country_options", to="insurances.InsuranceType"),
                ),
            ],
        ),
    ]
