# Generated by Django 3.2.9 on 2022-05-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0002_alter_travelassistanceinsurance_options'),
    ]

    operations = [
    ]
