# Generated by Django 3.2.9 on 2022-05-24 12:37

from django.db import migrations, models
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0005_alter_travelassistanceinsurance_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE vrzktypeethiasassistance "
                        "ADD COLUMN IF NOT EXISTS autochassis VARCHAR(20)"
                    ),
                    reverse_sql=(
                        "ALTER TABLE vrzktypeethiasassistance "
                        "DROP COLUMN IF EXISTS autochassis"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='travelassistanceinsurance',
                    name='_vehicle_chassis_number',
                    field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(
                        blank=True,
                        db_column='autochassis',
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
