# Generated by Django 3.2.9 on 2022-05-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0006_auto_20220524_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelassistanceinsurance',
            options={'managed': False},
        ),
    ]
