# Generated by Django 3.2.9 on 2022-05-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0007_alter_travelassistanceinsurance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonmember',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='travelassistanceinsurance',
            options={'managed': True},
        ),
    ]
