# Generated by Django 3.2.9 on 2022-06-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0011_alter_equipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='inuits_id',
            field=models.UUIDField(blank=True, db_column='inuits_id', default=None, null=True),
        ),
    ]
