# Generated by Django 3.2.9 on 2022-06-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0012_auto_20220601_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'managed': False},
        ),
    ]
