# Generated by Django 3.2.9 on 2022-06-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0013_alter_equipment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporaryvehicleinsurance',
            options={'managed': True},
        ),
    ]
