# Generated by Django 3.2.9 on 2022-06-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_insurances', '0015_auto_20220607_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporaryvehicleinsurance',
            options={'managed': False},
        ),
    ]
