FROM python:3.9-slim

# Prevents .pyc files
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Create work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Django project
COPY verzekeringen_api/ .

# Run the development server by default
CMD sh -c "python verzekeringen_api/manage.py migrate && \
python verzekeringen_api/manage.py collectstatic --noinput && \
python verzekeringen_api/manage.py addinsurancetypes && \
python verzekeringen_api/manage.py addinfovariables && \
python verzekeringen_api/manage.py importinitialcountries && \
python verzekeringen_api/manage.py runserver 0.0.0.0:8000"