from .inuits_abstract_person_serializer import InuitsAbstractPersonSerializer
from .inuits_non_member_serializer import InuitsNonMemberSerializer
from .inuits_claim_victim_serializer import InuitsClaimVictimSerializer
from .person_serializer import PersonSerializer
