# Generated by Django 3.2.8 on 2021-11-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoutsuser',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
