# Generated by Django 3.2.4 on 2021-07-26 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurances', '0012_alter_insuranceclaim_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaimAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'tiff', 'odt', 'pptx', 'docx', 'pdf'])])),
                ('content_type', models.CharField(max_length=100)),
                ('insurance_claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='insurances.insuranceclaim')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
