# Generated by Django 3.2.5 on 2021-08-11 12:58

import django.core.validators
from django.db import migrations, models

from inuits.files.validators import validate_file_extension


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceclaimattachment",
            name="file",
            field=models.FileField(upload_to="", validators=[validate_file_extension]),
        ),
    ]
