from . import base_insurance_service as BaseInsuranceService
from . import activity_insurance_service as ActivityInsuranceService
from . import temporary_insurance_service as TemporaryInsuranceService
from . import travel_assistance_insurance_service as TravelAssistanceInsuranceService
from . import temporary_vehicle_insurance_service as TemporaryVehicleInsuranceService
from . import event_insurance_service as EventInsuranceService
from . import equipment_insurance_service as EquipmentInsuranceService
from . import insurance_draft_service as InsuranceDraftService
from . import insurance_claim_service as InsuranceClaimService
from .insurance_claim_mail_service import InsuranceClaimMailService
