# Generated by Django 3.2.9 on 2022-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='involved_party',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='leadership',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='official_report',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='witness',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
