from .insurance_type_viewset import InsuranceTypeViewSet
from .insurance_viewset import InsuranceViewSet
from .insurance_draft_viewset import InsuranceDraftViewSet
from .insurance_claim_viewset import InsuranceClaimViewSet
from .insurance_claim_attachment_viewset import InsuranceClaimAttachmentViewSet
from .enum_viewsets import *
from .event_insurance_attachment_viewset import EventInsuranceAttachmentViewSet
from .activity_insurance_attachment_viewset import ActivityInsuranceAttachmentViewSet
