# Generated by Django 3.2.2 on 2021-06-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InuitsVehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Personenwagen', 'Personenwagen (maximum 5 passagiers)'), ('Minibus', 'Minibus (maximum 8 passagiers)'), ('Vrachtwagen tot 3.5 ton', 'Vrachtwagen tot 3.5 ton (maximum 8 passagiers)')], max_length=30)),
                ('brand', models.CharField(max_length=15)),
                ('license_plate', models.CharField(max_length=10)),
                ('construction_year', models.DateField()),
                ('chassis_number', models.CharField(max_length=20)),
                ('trailer', models.BooleanField(default=True)),
                ('group_number', models.CharField(max_length=6)),
            ],
        ),
    ]
