# Generated by Django 3.2.9 on 2021-12-07 00:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import scouts_auth.inuits.models.fields.django_shorthand_model_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scouts_insurances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InuitsEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nature', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('owner_member_group_admin_id', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=255, null=True)),
                ('owner_group_group_admin_id', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=6, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_inuitsequipment_created', to=settings.AUTH_USER_MODEL, verbose_name='Instance created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InuitsVehicle',
            fields=[
                ('inuits_vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, choices=[('PERSONENWAGEN', 'Personenwagen (maximum 5 inzittenden)'), ('MINIBUS', 'Minibus (maximum 8 inzittenden)'), ('VRACHTWAGEN', 'Vrachtwagen tot 3.5 ton (maximum 8 inzittenden)')], max_length=30)),
                ('brand', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=15)),
                ('license_plate', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=10)),
                ('construction_year', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('chassis_number', scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=20)),
                ('trailer', models.CharField(choices=[('0', 'Geen'), ('2', '<750kg'), ('3', '>750kg')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='InuitsVehicleTemplate',
            fields=[
                ('temporary_vehicle_insurance', models.OneToOneField(db_constraint=django.db.models.constraints.UniqueConstraint, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scouts_insurances.temporaryvehicleinsurance')),
                ('inuits_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.inuitsvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='InuitsEquipmentTemplate',
            fields=[
                ('equipment', models.OneToOneField(db_constraint=django.db.models.constraints.UniqueConstraint, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scouts_insurances.equipment')),
                ('inuits_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.inuitsequipment')),
            ],
        ),
    ]
