# Generated by Django 3.2.2 on 2021-06-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsvehicle',
            name='trailer',
            field=models.CharField(choices=[('0', 'OPTION0'), ('1', 'OPTION1'), ('2', 'OPTION2'), ('3', 'OPTION3')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='inuitsvehicle',
            name='type',
            field=models.CharField(choices=[('PERSONENWAGEN', 'Personenwagen (maximum 5 passagiers)'), ('MINIBUS', 'Minibus (maximum 8 passagiers)'), ('VRACHTWAGEN', 'Vrachtwagen tot 3.5 ton (maximum 8 passagiers)')], max_length=30),
        ),
    ]
