# Generated by Django 3.2.9 on 2021-11-26 00:35

import django.core.validators
from django.db import migrations
import inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_inuitsequipment_owner_non_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsvehicle',
            name='chassis_number',
            field=inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inuitsvehicle',
            name='construction_year',
            field=inuits.models.fields.django_shorthand_model_fields.OptionalIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
