# Generated by Django 3.2.2 on 2021-06-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20210607_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsvehicle',
            name='trailer',
            field=models.CharField(choices=[('0', 'Geen'), ('1', 'Onbekend gewicht'), ('2', '<750kg'), ('3', '>750kg')], default='0', max_length=1),
        ),
    ]
