# Generated by Django 3.2.9 on 2022-10-26 08:17

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsvehicle',
            name='type',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultCharField(blank=True, choices=[('PERSONENWAGEN', 'Personenwagen (max. 4+1 inzittenden)'), ('MINIBUS', 'Minibus (max. 8+1 inzittenden)'), ('VRACHTWAGEN', 'Lichte vrachtauto tot 3,5 ton (max. 8+1 inzittenden)')], db_column='autotype', default='PERSONENWAGEN', max_length=30),
        ),
    ]
