# Generated by Django 3.2.2 on 2021-06-14 11:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210610_1500'),
        ('equipment', '0003_alter_inuitsvehicle_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(db_column='materiaalid', primary_key=True, serialize=False)),
                ('nature', models.CharField(blank=True, db_column='aard', max_length=50)),
                ('description', models.CharField(db_column='materieomschrijving', max_length=500)),
                ('_amount', models.IntegerField(db_column='aantal', default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_value', models.DecimalField(db_column='nieuwwaardeperstuk', decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'db_table': 'vrzkmateriaal',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='inuitsvehicle',
            name='trailer',
            field=models.CharField(choices=[('0', 'Geen'), ('2', '<750kg'), ('3', '>750kg')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='InuitsEquipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nature', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('_amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('owner_member_group_admin_id', models.CharField(blank=True, db_column='ga_id', max_length=255, null=True)),
                ('group_number', models.CharField(max_length=6)),
                ('owner_non_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inuits_equipment', to='members.inuitsnonmember')),
            ],
        ),
    ]
