# Generated by Django 3.2.2 on 2021-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20210614_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inuitsequipment',
            name='nature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
