# Generated by Django 4.2.20 on 2025-05-23 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0004_alter_inuitsequipment_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inuitsvehicle",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instance created by",
            ),
        ),
        migrations.AddField(
            model_name="inuitsvehicle",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inuitsvehicle",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instance last update by",
            ),
        ),
        migrations.AddField(
            model_name="inuitsvehicle",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
