# Generated by Django 3.2.5 on 2021-08-31 22:50

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0024_alter_insuranceclaim_damage_type'),
        ('equipment', '0006_alter_inuitsvehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInuitsTemplate',
            fields=[
                ('temporary_vehicle_insurance', models.OneToOneField(db_constraint=django.db.models.constraints.UniqueConstraint, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='insurances.temporaryvehicleinsurance')),
                ('inuits_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.inuitsvehicle')),
            ],
        ),
    ]
