# Generated by Django 3.2.2 on 2021-05-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_admin_id',
            field=models.CharField(blank=True, db_column='ga_id', max_length=255),
        ),
    ]
